### ISSUE TITLE
potential to make `community` an external dependency?

### ISSUE THREAD

**Issue by ajschumacher** [dfreelon/TSM#2]
I see that the Louvain `community` package is on PyPI: https://pypi.python.org/pypi/python-louvain/0.3

Is the problem that it doesn't work with Python 3? I wonder if it's worth me experimenting a little bit; the latest version might work, or it might be possible to get Py3 fixes into the main distribution of `community`, which would mean less complexity for `TSM` to manage. What do you think?

**Comment by dfreelon** [comment]
When I added it, it was 2.7-only, and now only 2.7 is listed as a compatible Python version. It's fine with me if you want to test it. The Py3 fixes are very easy to make--in fact I've already made them in my "community3.py" modified version. Most are related to the print function.

**Comment by ajschumacher** [comment]
Cool - I'll put it on my to-do list! :smile:

**Comment by ajschumacher** [comment]
I just ran the test suite for the current version of `python-louvain` in Python 3.4.2 and it worked fine, aside from one warning... I opened an issue in their bitbucket asking about Py3 support: https://bitbucket.org/taynaud/python-louvain/issue/17/python-3

I hope to hear back from them; otherwise I think I may start adding some tests for TSM so that I'll know if I break anything.

Do you remember what sort(s) of problems you had with the `python-louvain` with Python 3?

**Comment by dfreelon** [comment]
The shell choked because of incompatible print statements. But I didn't build the package from scratch--I just downloaded the community.py file and tried to run it, then I fixed it for 3.

**Comment by ajschumacher** [comment]
I just took a look at the current `community` code's [main](https://bitbucket.org/taynaud/python-louvain/src/147f0973771485ce1b45c89c1e2766f94efaa4d4/community/__init__.py#cl-522), and it looks like it's converted to using `print` as a function (with parentheses) which makes me even more optimistic that it may be fully functional in Python 3! :smiley:

**Comment by dfreelon** [comment]
Great!

**Comment by ajschumacher** [comment]
Aynaud updated `community` to explicitly support Python 3!

https://bitbucket.org/taynaud/python-louvain/issue/17/python-3

I think it would be nice to switch over to using it as an installed dependency but I'm not sure I know how to test that everything continues to work as expected at the moment. May be something to think on.

**Comment by dfreelon** [comment]
Thanks for the info. I'll look into testing it when I have time, which 
may not be until after classes are over. Thanks and hope things are 
going well in NY

On 3/11/2015 7:42 PM, Aaron Schumacher wrote:

> Aynaud updated |community| to explicitly support Python 3!
> 
> https://bitbucket.org/taynaud/python-louvain/issue/17/python-3
> 
> I think it would be nice to switch over to using it as an installed 
> dependency but I'm not sure I know how to test that everything 
> continues to work as expected at the moment. May be something to think on.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dfreelon/TSM/issues/2#issuecomment-78388812.

## 

Deen Freelon
Assistant Professor
American University School of Communication
Office: McKinley 325
http://dfreelon.org/
@dfreelon
