### ISSUE TITLE
`load_data` returns empty lists for trailing newlines/null bytes

### ISSUE THREAD

**Issue by ajschumacher** [dfreelon/TSM#3]
I'm writing some tests and came across this screwy situation - if a file ends with "blah\n\0" it should probably not return a final empty list (`..., []]`) but that is the current behavior.

Alternatives:
- Not worry about this at all (keep current behavior).
- Load the file completely and do a global `.replace` to eliminate null bytes, rather than a line-by-line one.
- Include a check so that empty lines are never included. This would allow blank lines anywhere in a file, including trailing newlines.
- Eliminate the removal of null bytes (treat null bytes in files as bad input that needs to be dealt with before using TSM).

There are probably other options that I'm not thinking of. What do you think? Why is the replacement of null bytes in there to begin with?

**Comment by dfreelon** [comment]
Remove the null byte replacement and try running a csv thru it containing a null byte and see what happens. 

On February 22, 2015 6:32:02 PM EST, Aaron Schumacher notifications@github.com wrote:

> I'm writing some tests and came across this screwy situation - if a
> file ends with "blah\n\0" it should probably not return a final empty
> list (`..., []]`) but that is the current behavior.
> 
> Alternatives:
> - Not worry about this at all (keep current behavior).
> - Load the file completely and do a global `.replace` to eliminate null
>   bytes, rather than a line-by-line one.
> - Include a check so that empty lines are never included. This would
>   allow blank lines anywhere in a file, including trailing newlines.
> - Eliminate the removal of null bytes (treat null bytes in files as bad
>   input that needs to be dealt with before using TSM).
> 
> There are probably other options that I'm not thinking of. What do you
> think? Why is the replacement of null bytes in there to begin with?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dfreelon/TSM/issues/3

## 

Deen Freelon
Assistant Professor
School of Communication
American University
Office: McKinley 325
http://dfreelon.org

**Comment by ajschumacher** [comment]
`csv.reader` will fail on null bytes; that's the fourth option I listed. It would mean that users would have to remove null bytes from their input files before using TSM. Is that the desired behavior? I think it's a good choice, but wanted to check with you. (The tests I just wrote currently check that TSM does remove null bytes.)

**Comment by dfreelon** [comment]
I don't think forcing users to remove null bytes manually is a good idea.       In a file with millions of lines it could be a pain. I'd rather come up with a solution that boots null bytes without requiring user intervention. 

On February 22, 2015 6:57:06 PM EST, Aaron Schumacher notifications@github.com wrote:

> `csv.reader` will fail on null bytes; that's the fourth option I
> listed. It would mean that users would have to remove null bytes from
> their input files before using TSM. Is that the desired behavior? I
> think it's a good choice, but wanted to check with you. (The tests I
> just wrote currently check that TSM does remove null bytes.)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dfreelon/TSM/issues/3#issuecomment-75473726

## 

Deen Freelon
Assistant Professor
School of Communication
American University
Office: McKinley 325
http://dfreelon.org

**Comment by ajschumacher** [comment]
Cool - of the first three options then, which do you prefer?

**Comment by dfreelon** [comment]
I wouldn't mind #3 as long as omitting lines containing null bytes would never lead to data loss, but I don't know that that's the case. #2 seems like it could introduce a performance hit, esp with very large files, but maybe not. 

On February 22, 2015 6:32:02 PM EST, Aaron Schumacher notifications@github.com wrote:

> I'm writing some tests and came across this screwy situation - if a
> file ends with "blah\n\0" it should probably not return a final empty
> list (`..., []]`) but that is the current behavior.
> 
> Alternatives:
> - Not worry about this at all (keep current behavior).
> - Load the file completely and do a global `.replace` to eliminate null
>   bytes, rather than a line-by-line one.
> - Include a check so that empty lines are never included. This would
>   allow blank lines anywhere in a file, including trailing newlines.
> - Eliminate the removal of null bytes (treat null bytes in files as bad
>   input that needs to be dealt with before using TSM).
> 
> There are probably other options that I'm not thinking of. What do you
> think? Why is the replacement of null bytes in there to begin with?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/dfreelon/TSM/issues/3

## 

Deen Freelon
Assistant Professor
School of Communication
American University
Office: McKinley 325
http://dfreelon.org

**Comment by ajschumacher** [comment]
Sounds good; option 3 shouldn't lead to any data loss, since null bytes aren't going to be data anyway, and empty lines won't be meaningful for CSV (an empty line is different from a row with blanks, since the commas will still be in there).

**Comment by ajschumacher** [comment]
I'll write it up as a pull request after the first round of tests are merged in, if they look good to you~

**Comment by dfreelon** [comment]
I don't believe this is true. Take a look at the attached screenshot--it 
is of the file that originally prompted me to add the null byte replace. 
As you can see, there is a series of null bytes on line 59157 right in 
the middle of the tweet. Basically the issue is that null bytes are not 
coextensive with empty lines. For that reason I don't want to add any 
code that removes entire lines if they contain null bytes.

I need a solution that can strip all null bytes without yielding an 
empty list if the null byte is at the end. Would adding a newline (or 
other character) at the end of the file before running the replace work?

On 2/22/2015 8:58 PM, Aaron Schumacher wrote:

> Sounds good; option 3 shouldn't lead to any data loss, since null 
> bytes aren't going to be data anyway, and empty lines won't be 
> meaningful for CSV (an empty line is different from a row with blanks, 
> since the commas will still be in there).
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dfreelon/TSM/issues/3#issuecomment-75479797.

## 

Deen Freelon
Assistant Professor
American University School of Communication
Office: McKinley 325
http://dfreelon.org/
@dfreelon

**Comment by dfreelon** [comment]
Screenshot
![screenshot 2015-02-23 09 35 56](https://cloud.githubusercontent.com/assets/6620439/6329671/864a29e2-bb40-11e4-9355-02311ced6d5e.png)

**Comment by ajschumacher** [comment]
I think if we strip out the null bytes and then do the check for emptiness, we should have the behavior you want. A line like line 59157 in your screenshot would have its nulls removed and be entered as a data row, as desired. The only thing that would be dropped would be a blank line or a line that is all null byte(s), because the null bytes would be removed and then the line would be empty. Does that work?

**Comment by dfreelon** [comment]
Okay, go for it and I'll test your change on my file.

On 2/23/2015 9:51 AM, Aaron Schumacher wrote:

> I think if we strip out the null bytes and then do the check for 
> emptiness, we should have the behavior you want. A line like line 
> 59157 in your screenshot would have its nulls removed and be entered 
> as a data row, as desired. The only thing that would be dropped would 
> be a blank line or a line that is all null byte(s), because the null 
> bytes would be removed and then the line would be empty. Does that work?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dfreelon/TSM/issues/3#issuecomment-75554345.

## 

Deen Freelon
Assistant Professor
American University School of Communication
Office: McKinley 325
http://dfreelon.org/
@dfreelon

**Comment by ajschumacher** [comment]
Cool - will do! I might work on it on Thursday; possibly sooner if I can. (Maybe at Code for DC?) The current [pull request](https://github.com/dfreelon/TSM/pull/4) just adds some tests; I think it should be ready to merge now if you want to take a look. Thanks!

**Comment by dfreelon** [comment]
Great, thanks, did the merge. Hey, when you get a chance, could you 
rename the file "test_tsm.py" to something more descriptive? It's 
currently very similar to "tsm_test2.py" which is a very basic test file 
intended to be used with real data.

On 2/23/2015 10:01 AM, Aaron Schumacher wrote:

> Cool - will do! I might work on it on Thursday; possibly sooner if I 
> can. (Maybe at Code for DC?) The current pull request 
> https://github.com/dfreelon/TSM/pull/4 just adds some tests; I think 
> it should be ready to merge now if you want to take a look. Thanks!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/dfreelon/TSM/issues/3#issuecomment-75556837.

## 

Deen Freelon
Assistant Professor
American University School of Communication
Office: McKinley 325
http://dfreelon.org/
@dfreelon

**Comment by ajschumacher** [comment]
Good point! Definitely that, and I think it might make sense to move several files around in the near future, with the goal of packaging into a module that can be put on PyPI and loaded via `pip`.

**Comment by ajschumacher** [comment]
I'll also rename the `test_tsm.py` file like you suggested in this next PR...
