### ISSUE TITLE
Add in scratch CSV file for showing raw data directly

### ISSUE THREAD

**Issue by DGaffney** [dfreelon/TSM#7]
Hey Deen,

I've talked to you before many many years ago - hope all is well. I was wondering if you could add something very trivial to the md file - I figured out how to get my data to look the way you wanted it by reading your code in the first of the two ipython notebooks (after of course upgrading my ipython), but I worry that not as many people will adopt this tool (which is great) because of the barrier - perhaps adding a very small example file like the below and providing a usage script will make this more immediately obvious to use?

``` csv
dgaff,"Twitter is pretty fun, isn't it, @dfreelon?",2015-09-01
dfreelon,Yes indeed @dgaff - @some_other_user weigh in?,2015-09-02
some_other_user,Of course twitter is grand. Mostly because of @dril.,2015-09-02
dril,Some weird tweet no one understands but everyone favorites @some_other_user,2015-09-02
cnnbrk,Looks like @dril just tweeted,2015-09-03
```

**Comment by dfreelon** [comment]
Hi Devin, good to hear from you. I will try to add your suggested data this week. Also, the date column isn't strictly necessary, but it can be useful if you want to use match_communities.

I'm curious--what kinds of research are you using TSM for? I don't know much about its users, or even if it has any besides me. I'd love to hear about your use case(s) if you have time. Best, ~DEEN

**Comment by DGaffney** [comment]
Hey Deen,

Good for the extra clarity on the date column. I just added it in my own CSV because I didn't want to run into any other errors. My example above is just a throwaway example - anything will do as long as it provides a clear example for how people have to get their data to look like. I am using TSM at this moment to use your intermediaries function while analyzing the overlap between the #BaltimoreUprising and #BaltimoreRiot hashtags with Brooke Foucault-Welles. Specifically, these are the functions I'm playing with today (along with the comments I made in my code for Brooke as getting to Python 3 may not be something she (or other potential users) has done):

``` python
# This needs python3 - https://www.python.org/downloads/release/python-343/
# Open a new terminal after installing this, then run the following:
# python3 -m pip install networkx
# python3 -m pip install python-louvain
# python3 -m pip install twarc
# python3 -m pip install ipython
# Then type `python3` and you're good to go on the command line to run code like the below:
import tsm
raw = tsm.load_data("tsm_data.csv")
edges = tsm.t2e(raw)
communities = tsm.get_top_communities(edges)
intermediaries = tsm.get_intermediaries(communities.node_list, edges)
for i in intermediaries:
  print(i[1])
```

**Comment by dfreelon** [comment]
Interesting--I'm also using TSM to study some Black Lives Matter-related tweets, albeit from an earlier period. I'd be very interested to know if you end up publishing anything based on results gleaned through TSM. 

I also have an in-press book chapter that explains how to use TSM and gives a theoretical justification for it (the iPython notebooks are meant to accompany the chapter). I can send you a copy if you're interested. It's actually for a volume Brooke is editing with Sandra Gonzalez-Bailon.

Feel free to let me know if you have any more questions about TSM or how to use it.

**Comment by DGaffney** [comment]
Hah - I think I know about that volume :)

I think I have my head around it for now, but I'll let you know - if we find anything interesting you'll be the first to know!

**Comment by dfreelon** [comment]
Okay, added your sample to the README minus the dates.
